// TzGen: writes src/NeonCompanion/Llm/Tools/WindowsZones.cs, the IANA → Windows time zone table
// the clock tools use to resolve "Asia/Tokyo" to "Tokyo Standard Time".
//
// Why a table: the app runs with InvariantGlobalization=true, and without ICU
// TimeZoneInfo.FindSystemTimeZoneById on Windows knows only Windows ids (measured 2026-09-11:
// "Asia/Tokyo" throws TimeZoneNotFoundException, TryConvertIanaIdToWindowsId returns false).
// A model knows IANA names; ICU's own answer is CLDR's windowsZones.xml, so the same data is
// embedded instead.
//
// CLDR keys zones by their old IANA spellings (Asia/Calcutta, Europe/Kiev) while a model sends
// the current ones (Asia/Kolkata, Europe/Kyiv), so the IANA `backward` link file is folded in:
// every link name and link target that shares a mapping gets the same Windows id.
//
// A .NET 10 file-based app: no csproj, not in the solution, not run by build.ps1. The output is
// committed; run this only to pick up a new CLDR or tz release, from the repository root:
//
//     dotnet run tools/TzGen.cs                        # downloads both files, writes the table
//     dotnet run tools/TzGen.cs -- --xml <windowsZones.xml> --links <backward> [--out <path>]

using System.Text;
using System.Xml.Linq;

const string SourceUrl = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml";
const string LinksUrl = "https://raw.githubusercontent.com/eggert/tz/main/backward";

var xmlPath = Arg("--xml");
var linksPath = Arg("--links");
var outPath = Arg("--out") ?? "src/NeonCompanion/Llm/Tools/WindowsZones.cs";

using var http = new HttpClient();
string xml = xmlPath is not null ? File.ReadAllText(xmlPath) : await http.GetStringAsync(SourceUrl);
string links = linksPath is not null ? File.ReadAllText(linksPath) : await http.GetStringAsync(LinksUrl);

var document = XDocument.Parse(xml);
var mapTimezones = document.Descendants("mapTimezones").Single();
string typeVersion = (string?)mapTimezones.Attribute("typeVersion") ?? "unknown";

// One IANA id can appear under several territories; the first mapping wins and they never
// disagree on the Windows id. The Windows id itself is also a valid key, so the tool can take
// either form through one lookup.
var map = new SortedDictionary<string, string>(StringComparer.Ordinal);
foreach (var zone in mapTimezones.Elements("mapZone"))
{
    string windows = (string)zone.Attribute("other")!;
    foreach (var iana in ((string)zone.Attribute("type")!).Split(' ', StringSplitOptions.RemoveEmptyEntries))
    {
        map.TryAdd(iana, windows);
    }
}

// "Link<tab>TARGET<tab>LINK-NAME": whichever side CLDR knows lends its Windows id to the other.
// Repeated until stable, since a link's target can itself be a link.
int aliases = 0;
var linkPairs = links.Split('\n')
    .Select(line => line.Split('#')[0].Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries))
    .Where(parts => parts.Length == 3 && parts[0] == "Link")
    .Select(parts => (Target: parts[1], Name: parts[2]))
    .ToList();
bool changed;
do
{
    changed = false;
    foreach (var (target, name) in linkPairs)
    {
        if (map.TryGetValue(target, out var windows) && map.TryAdd(name, windows)) { aliases++; changed = true; }
        else if (map.TryGetValue(name, out windows) && map.TryAdd(target, windows)) { aliases++; changed = true; }
    }
}
while (changed);

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("// Generated by tools/TzGen.cs from CLDR windowsZones.xml (typeVersion " + typeVersion + ") plus the IANA backward links.");
sb.AppendLine("// Do not edit; rerun `dotnet run tools/TzGen.cs` from the repository root instead.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace NeonCompanion.Llm.Tools;");
sb.AppendLine();
sb.AppendLine("/// <summary>");
sb.AppendLine("/// IANA → Windows time zone ids (CLDR's mapping, the same data ICU serves), because under");
sb.AppendLine("/// <c>InvariantGlobalization</c> <see cref=\"TimeZoneInfo.FindSystemTimeZoneById\"/> knows only the");
sb.AppendLine("/// Windows form. Current and old IANA spellings both resolve (the IANA backward links are");
sb.AppendLine("/// folded in). Keys are compared ordinally, case-insensitive.");
sb.AppendLine("/// </summary>");
sb.AppendLine("public static class WindowsZones");
sb.AppendLine("{");
sb.AppendLine("    /// <summary>The CLDR <c>typeVersion</c> the table was generated from.</summary>");
sb.AppendLine("    public const string Version = \"" + typeVersion + "\";");
sb.AppendLine();
sb.AppendLine("    /// <summary>The Windows id for an IANA id, or false when CLDR has no mapping.</summary>");
sb.AppendLine("    public static bool TryGetWindowsId(string ianaId, out string windowsId)");
sb.AppendLine("    {");
sb.AppendLine("        ArgumentNullException.ThrowIfNull(ianaId);");
sb.AppendLine("        return Map.TryGetValue(ianaId, out windowsId!);");
sb.AppendLine("    }");
sb.AppendLine();
sb.AppendLine("    /// <summary>How many IANA ids the table knows.</summary>");
sb.AppendLine("    public static int Count => Map.Count;");
sb.AppendLine();
sb.AppendLine("    private static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)");
sb.AppendLine("    {");
foreach (var (iana, windows) in map)
{
    sb.AppendLine("        [\"" + iana + "\"] = \"" + windows + "\",");
}

sb.AppendLine("    };");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outPath))!);
File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {outPath}: {map.Count} IANA ids ({aliases} from backward links), CLDR typeVersion {typeVersion}.");
return 0;

string? Arg(string name)
{
    var args = Environment.GetCommandLineArgs();
    for (int i = 0; i < args.Length - 1; i++)
    {
        if (args[i] == name)
        {
            return args[i + 1];
        }
    }

    return null;
}
